### ISSUE TITLE
knode

### ISSUE THREAD

**Issue by hackervera** [weepy/kaffeine#27]
redis = require 'redis'
client = redis.createClient()
foo = client.get! 'foo'

mini:~ tyler$ knode test.kaf
/Users/tyler/test.kaf:1
 require 'redis'
         ^^^^^^^

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
SyntaxError: Unexpected string
    at Module._compile (module.js:399:25)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at require (module.js:348:19)
    at Object.<anonymous> (/usr/local/lib/node/.npm/kaffeine/0.0.8/package/bin/knode:13:1)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)

**Comment by weepy** [comment]
hi. you need to name the file test.k

kaffeine tells node to compile files with a .k as kaffeine,  but I think .kaf will be treated as plain JavaScript, hence the error

**Comment by hackervera** [comment]
I _just_ discovered this, right before you posted. Thanks!

**Comment by weepy** [comment]
great stuff ! let me know how you get on with kaffeine!
